service: serverless-api-monkey-sanctuary

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  stage: dev

functions:
  express:
    handler: handler.app
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'